os: osx
language: csharp
solution: ./ReorderableListEditor/ReorderableListEditor.sln
dotnet: 2.2.104
python: 3.7
mono: latest
env:
  - CONFIG_NAME=Release
  - CONFIG_NAME=Debug
before_install:
  - chmod a+x $LULLAPY_ROOT/*
install:
  - pip3 install -r requirements.txt
script:
  - python3 $LULLAPY_ROOT/netrestore.py -s "$TRAVIS_SOLUTION"
  - python3 $LULLAPY_ROOT/netbuild.py -s "$TRAVIS_SOLUTION" -c "c"
  - python3 $LULLAPY_ROOT/netcopy.py -a "$ASSEMBLY_NAME" -d "$ASSEMBLY_BIN_PATH/$CONFIG_NAME" -e "dll;xml;pdb" -t "./unity-dirs.txt" -c
  - python3 $LULLAPY_ROOT/plainexist.py -f "./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.dll;./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.xml;./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.pdb"