os: osx
language: csharp
solution: ./ReorderableListEditor/ReorderableListEditor.sln
dotnet: 2.2.104
python: 3.7
mono: latest
before_install:
  - chmod a+x ./tools/*
install:
  - pip3 install -r requirements.txt
script:
  - python3 ./tools/netrestore.py -s "$TRAVIS_SOLUTION"
  - python3 ./tools/netbuild.py -s "$TRAVIS_SOLUTION" -c "Release"
  - python3 ./tools/netcopy.py -a "$ASSEMBLY_NAME" -d concat($ASSEMBLY_BIN_PATH, "Release") -e "dll;xml;pdb" -t "./tools/unity-dirs.txt" -c
  - python3 ./tools/plainexist.py -f "./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.dll;./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.xml;./ReorderableListEditor.Demo/Assets/Libraries/Andeart.ReorderableListEditor/Andeart.ReorderableListEditor.pdb"